package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "adm_libelle")
public class AdmLibelle implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "ADM_LIBELLE";

	public transient static final String _id = "ID";
	public transient static final String _code = "CODE";
	public transient static final String _valFr = "VAL_FR";
	public transient static final String _valAr = "VAL_AR";
	public transient static final String _ordre = "ORDRE";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType = new HashMap<String, String>() {
		{
			put(_id, "LONG");
		}
		{
			put(_code, "STRING");
		}
		{
			put(_valFr, "STRING");
		}
		{
			put(_valAr, "STRING");
		}
		{
			put(_ordre, "INTEGER");
		}
	};

				@GeneratedValue
			@Id
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "code", length = 50)
	private String code;

	@Column(name = "val_fr", length = 512)
	private String valFr;

	@Column(name = "val_ar", length = 512)
	private String valAr;

	@Column(name = "ordre")
	private Integer ordre;

	public AdmLibelle clone() throws CloneNotSupportedException {
		return (AdmLibelle) super.clone();
	}
}
