package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "adm_param", uniqueConstraints = @UniqueConstraint(columnNames = "cod_param"))
public class AdmParam implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "ADM_PARAM";

	public transient static final String _id = "ID";
	public transient static final String _codParam = "COD_PARAM";
	public transient static final String _valParam = "VAL_PARAM";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType = new HashMap<String, String>() {
		{
			put(_id, "LONG");
		}
		{
			put(_codParam, "STRING");
		}
		{
			put(_valParam, "STRING");
		}
	};
				@GeneratedValue
			@Id
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "cod_param", unique = true, length = 50)
	private String codParam;

	@Column(name = "val_param", length = 256)
	private String valParam;

	public AdmParam clone() throws CloneNotSupportedException {
		return (AdmParam) super.clone();
	}
}
