package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "adm_profession", uniqueConstraints = @UniqueConstraint(columnNames = "cod_profes"))
public class AdmProfession implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "ADM_PROFESSION";

	public transient static final String _idProfes = "ID_PROFES";
	public transient static final String _codProfes = "COD_PROFES";
	public transient static final String _desProfes = "DES_PROFES";
	public transient static final String _desProfesAr = "DES_PROFES_AR";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType = new HashMap<String, String>() {
		{
			put(_idProfes, "LONG");
		}
		{
			put(_codProfes, "STRING");
		}
		{
			put(_desProfes, "STRING");
		}
		{
			put(_desProfesAr, "STRING");
		}
	};

	@SequenceGenerator(allocationSize = 1, initialValue = 1, sequenceName = "adm_seq_gen", name = "adm_seq_gen")
	@GeneratedValue(generator = "adm_seq_gen", strategy = GenerationType.SEQUENCE)
	@Id
	@Column(name = "id_profes", unique = true, nullable = false)
	private Long idProfes;

	@Column(name = "cod_profes", unique = true, nullable = false, length = 40)
	private String codProfes;

	@Column(name = "des_profes", nullable = false, length = 300)
	private String desProfes;

	@Column(name = "des_profes_ar", nullable = false, length = 300)
	private String desProfesAr;

	public AdmProfession clone() throws CloneNotSupportedException {
		return (AdmProfession) super.clone();
	}
}
