package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "v_adm_fonc_profil")
public class VAdmFoncProfil implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "V_ADM_FONC_PROFIL";

	public transient static final String _idFoncProfil = "ID_FONC_PROFIL";
	public transient static final String _idFonc = "ID_FONC";
	public transient static final String _idProfil = "ID_PROFIL";
	public transient static final String _FEditer = "F_EDITER";
	public transient static final String _FValider = "F_VALIDER";
	public transient static final String _idAppProfil = "ID_APP_PROFIL";
	public transient static final String _codProfil = "COD_PROFIL";
	public transient static final String _desProfil = "DES_PROFIL";
	public transient static final String _desProfilAr = "DES_PROFIL_AR";
	public transient static final String _FActif = "F_ACTIF";
	public transient static final String _desFrActif = "DES_FR_ACTIF";
	public transient static final String _desArActif = "DES_AR_ACTIF";
	public transient static final String _datCreat = "DAT_CREAT";
	public transient static final String _datDerModif = "DAT_DER_MODIF";
	public transient static final String _codApp = "COD_APP";
	public transient static final String _desApp = "DES_APP";
	public transient static final String _desAppAr = "DES_APP_AR";
	public transient static final String _idParent = "ID_PARENT";
	public transient static final String _idAppFonc = "ID_APP_FONC";
	public transient static final String _cod = "COD";
	public transient static final String _label = "LABEL";
	public transient static final String _action = "ACTION";
	public transient static final String _icon = "ICON";
	public transient static final String _FAffMenu = "F_AFF_MENU";
	public transient static final String _FAffEtat = "F_AFF_ETAT";
	public transient static final String _FAdmin = "F_ADMIN";
	public transient static final String _desFonc = "DES_FONC";
	public transient static final String _desFoncAr = "DES_FONC_AR";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType = new HashMap<String, String>() {
		{
			put(_idFoncProfil, "LONG");
		}
		{
			put(_idFonc, "LONG");
		}
		{
			put(_idProfil, "LONG");
		}
		{
			put(_FEditer, "INTEGER");
		}
		{
			put(_FValider, "INTEGER");
		}
		{
			put(_idAppProfil, "LONG");
		}
		{
			put(_codProfil, "STRING");
		}
		{
			put(_desProfil, "STRING");
		}
		{
			put(_desProfilAr, "STRING");
		}
		{
			put(_FActif, "INTEGER");
		}
		{
			put(_desFrActif, "STRING");
		}
		{
			put(_desArActif, "STRING");
		}
		{
			put(_datCreat, "DATE");
		}
		{
			put(_datDerModif, "DATE");
		}
		{
			put(_codApp, "STRING");
		}
		{
			put(_desApp, "STRING");
		}
		{
			put(_desAppAr, "STRING");
		}
		{
			put(_idParent, "LONG");
		}
		{
			put(_idAppFonc, "LONG");
		}
		{
			put(_cod, "STRING");
		}
		{
			put(_label, "STRING");
		}
		{
			put(_action, "STRING");
		}
		{
			put(_icon, "STRING");
		}
		{
			put(_FAffMenu, "LONG");
		}
		{
			put(_FAffEtat, "LONG");
		}
		{
			put(_FAdmin, "LONG");
		}
		{
			put(_desFonc, "STRING");
		}
		{
			put(_desFoncAr, "STRING");
		}
	};
	@GeneratedValue
	@Id
	@Column(name = "id_fonc_profil")
	private Long idFoncProfil;

	@Column(name = "id_fonc")
	private Long idFonc;

	@Column(name = "id_profil")
	private Long idProfil;

	@Column(name = "f_editer", precision = 1, scale = 0)
	private Integer FEditer;

	@Column(name = "f_valider", precision = 1, scale = 0)
	private Integer FValider;

	@Column(name = "id_app_profil")
	private Long idAppProfil;

	@Column(name = "cod_profil", length = 40)
	private String codProfil;

	@Column(name = "des_profil", length = 300)
	private String desProfil;

	@Column(name = "des_profil_ar", length = 300)
	private String desProfilAr;

	@Column(name = "f_actif", precision = 1, scale = 0)
	private Integer FActif;

	@Column(name = "des_fr_actif", length = 512)
	private String desFrActif;

	@Column(name = "des_ar_actif", length = 512)
	private String desArActif;

	@Column(name = "dat_creat", length = 13)
	private Date datCreat;

	@Column(name = "dat_der_modif", length = 13)
	private Date datDerModif;

	@Column(name = "cod_app", length = 40)
	private String codApp;

	@Column(name = "des_app", length = 300)
	private String desApp;

	@Column(name = "des_app_ar", length = 300)
	private String desAppAr;

	@Column(name = "id_parent")
	private Long idParent;

	@Column(name = "id_app_fonc")
	private Long idAppFonc;

	@Column(name = "cod", length = 40)
	private String cod;

	@Column(name = "label", length = 300)
	private String label;

	@Column(name = "action", length = 300)
	private String action;

	@Column(name = "icon", length = 300)
	private String icon;

	@Column(name = "f_aff_menu")
	private Long FAffMenu;

	@Column(name = "f_aff_etat")
	private Long FAffEtat;

	@Column(name = "f_admin")
	private Long FAdmin;

	@Column(name = "des_fonc", length = 300)
	private String desFonc;

	@Column(name = "des_fonc_ar", length = 300)
	private String desFoncAr;

	public VAdmFoncProfil clone() throws CloneNotSupportedException {
		return (VAdmFoncProfil) super.clone();
	}
}
