package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "v_adm_log_data")
public class VAdmLogData implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "V_ADM_LOG_DATA";

	public transient static final String _idLog = "ID_LOG";
	public transient static final String _datLog = "DAT_LOG";
	public transient static final String _timeLog = "TIME_LOG";
	public transient static final String _sessionId = "SESSION_ID";
	public transient static final String _remoteHost = "REMOTE_HOST";
	public transient static final String _remoteAddr = "REMOTE_ADDR";
	public transient static final String _browser = "BROWSER";
	public transient static final String _login = "LOGIN";
	public transient static final String _idUser = "ID_USER";
	public transient static final String _nom = "NOM";
	public transient static final String _typOp = "TYP_OP";
	public transient static final String _typOpFr = "TYP_OP_FR";
	public transient static final String _typOpAr = "TYP_OP_AR";
	public transient static final String _tableName = "TABLE_NAME";
	public transient static final String _data = "DATA";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType = new HashMap<String, String>() {
		{
			put(_idLog, "LONG");
		}
		{
			put(_datLog, "DATE");
		}
		{
			put(_timeLog, "STRING");
		}
		{
			put(_sessionId, "STRING");
		}
		{
			put(_remoteHost, "STRING");
		}
		{
			put(_remoteAddr, "STRING");
		}
		{
			put(_browser, "STRING");
		}
		{
			put(_login, "STRING");
		}
		{
			put(_idUser, "LONG");
		}
		{
			put(_nom, "STRING");
		}
		{
			put(_typOp, "STRING");
		}
		{
			put(_typOpFr, "STRING");
		}
		{
			put(_typOpAr, "STRING");
		}
		{
			put(_tableName, "STRING");
		}
		{
			put(_data, "STRING");
		}
	};

				@GeneratedValue
			@Id
	@Column(name = "id_log")
	private Long idLog;

	@Column(name = "dat_log", length = 13)
	private Date datLog;

	@Column(name = "time_log", length = 8)
	private String timeLog;

	@Column(name = "session_id", length = 100)
	private String sessionId;

	@Column(name = "remote_host", length = 40)
	private String remoteHost;

	@Column(name = "remote_addr", length = 40)
	private String remoteAddr;

	@Column(name = "browser", length = 40)
	private String browser;

	@Column(name = "login", length = 200)
	private String login;

	@Column(name = "id_user")
	private Long idUser;

	@Column(name = "nom", length = 200)
	private String nom;

	@Column(name = "typ_op", length = 20)
	private String typOp;

	@Column(name = "typ_op_fr", length = 512)
	private String typOpFr;

	@Column(name = "typ_op_ar", length = 512)
	private String typOpAr;

	@Column(name = "table_name", length = 100)
	private String tableName;

	@Column(name = "data")
	private String data;

	public VAdmLogData clone() throws CloneNotSupportedException {
		return (VAdmLogData) super.clone();
	}
}
