package tn.com.st2i.prj.admin.model;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 * 
 * Postgres dataBase
 *
 */
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.SequenceGenerator;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import java.util.HashMap;
import java.util.Map;

import lombok.Data;

@Data
@Entity
@Table(name = "v_adm_profil")
public class VAdmProfil implements java.io.Serializable, Cloneable {
	private transient static final long serialVersionUID = 1L;

	public transient static final String _nameTable = "V_ADM_PROFIL";

	public transient static final String _idProfil = "ID_PROFIL";
	public transient static final String _idApp = "ID_APP";
	public transient static final String _codProfil = "COD_PROFIL";
	public transient static final String _desProfil = "DES_PROFIL";
	public transient static final String _desProfilAr = "DES_PROFIL_AR";
	public transient static final String _FActif = "F_ACTIF";
	public transient static final String _desFrActif = "DES_FR_ACTIF";
	public transient static final String _desArActif = "DES_AR_ACTIF";
	public transient static final String _datCreat = "DAT_CREAT";
	public transient static final String _datDerModif = "DAT_DER_MODIF";
	public transient static final String _codApp = "COD_APP";
	public transient static final String _desApp = "DES_APP";
	public transient static final String _desAppAr = "DES_APP_AR";

	@SuppressWarnings("serial")
	public static transient final Map<String, String> listType=new HashMap<String,String>(){{put(_idProfil,"LONG");}{put(_idApp,"LONG");}{put(_codProfil,"STRING");}{put(_desProfil,"STRING");}{put(_desProfilAr,"STRING");}{put(_FActif,"INTEGER");}{put(_desFrActif,"STRING");}{put(_desArActif,"STRING");}{put(_datCreat,"DATE");}{put(_datDerModif,"DATE");}{put(_codApp,"STRING");}{put(_desApp,"STRING");}{put(_desAppAr,"STRING");}};

	@GeneratedValue
	@Id
	@Column(name = "id_profil")
	private Long idProfil;

	@Column(name = "id_app")
	private Long idApp;

	@Column(name = "cod_profil", length = 40)
	private String codProfil;

	@Column(name = "des_profil", length = 300)
	private String desProfil;

	@Column(name = "des_profil_ar", length = 300)
	private String desProfilAr;

	@Column(name = "f_actif", precision = 1, scale = 0)
	private Integer FActif;

	@Column(name = "des_fr_actif", length = 512)
	private String desFrActif;

	@Column(name = "des_ar_actif", length = 512)
	private String desArActif;

	@Column(name = "dat_creat", length = 13)
	private Date datCreat;

	@Column(name = "dat_der_modif", length = 13)
	private Date datDerModif;

	@Column(name = "cod_app", length = 40)
	private String codApp;

	@Column(name = "des_app", length = 300)
	private String desApp;

	@Column(name = "des_app_ar", length = 300)
	private String desAppAr;

	public VAdmProfil clone() throws CloneNotSupportedException {
		return (VAdmProfil) super.clone();
	}
}
