package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.AdmProfil;

public interface IAdmProfilDao extends IManagerDao<AdmProfil, Long> {
	public Boolean isCodeProfilUnique(String codProfil,Long idProfil);
}
