package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */

import java.math.BigDecimal;

import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.AdmUtilisateur;

public interface IAdmUtilisateurDao extends IManagerDao<AdmUtilisateur, Long> {

	public AdmUtilisateur findUserByLoginPwd(String login, String pwd);

	public AdmUtilisateur findUserByLogin(String login);

	public Boolean isLongUserUnique(String login, Long idUser);

	public void updateUserDateExpire(Long idUser);

		public Integer verifyUserEtat(Long idUser);
        	
	public void deleteUserCascadeById(Long idUser);

}
