package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.AdmLogData;

public interface IAdmLogDataDao extends IManagerDao<AdmLogData, Long> {
}
