package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.AdmProfession;

public interface IAdmProfessionDao extends IManagerDao<AdmProfession, Long> {

	public List<AdmProfession> getListProfessions();

	public List<TableGen> getListProfessions(String codProfes,
			String desProfes, Long idOtherProfes) throws Exception;
	
	public Boolean isCodeProfessionUnique(String codProfes, Long idProfes);

}
