package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.List;

import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.AdmApplication;

public interface IAdmApplicationDao extends IManagerDao<AdmApplication, Long> {

	public List<AdmApplication> getListApplications();

}
