package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.VAdmProfil;

public interface IVAdmProfilDao extends IManagerDao<VAdmProfil, Long> {

	public List<TableGen> getListVProfil(Long idApp, String code, String des,
			Long actif) throws Exception;

	public List<TableGen> getListVProfilActif(Long idApp, String code,
			String des) throws Exception;

}
