package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.Date;
import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.VAdmLogAcces;

public interface IVAdmLogAccesDao extends IManagerDao<VAdmLogAcces, Long> {
	public List<TableGen> getListLogAccess(String login, String nom,
			Date dateDebut, Date dateFin, String adr, Long idFonc,
			Long idParent, Boolean echec) throws Exception;
}
