package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.Date;
import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.VAdmLogData;

public interface IVAdmLogDataDao extends IManagerDao<VAdmLogData, Long> {
	public List<TableGen> getListLogData(String login, String nom,
			Date dateDebut, Date dateFin, String adr, String typeOp,
			String table) throws Exception;

	public List<TableGen> getListLogDataBySessionId(String sessionId)
			throws Exception;
}
