package tn.com.st2i.prj.admin.dao;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.Date;
import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.tools.IManagerDao;

import tn.com.st2i.prj.admin.model.VAdmUtilisateur;

public interface IVAdmUtilisateurDao extends IManagerDao<VAdmUtilisateur, Long> {

	public List<TableGen> getListVUtilisateurForSearch(String login, String name,
			String cin, Date dateDebutLastCnx, Date dateFinLastCnx,
			Long idProf, Long idEtat)
			throws Exception;

	public VAdmUtilisateur findVUserByLoginPwd(String login, String pwd);

}
