package tn.com.st2i.prj.admin.dao.impl;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.List;

import tn.com.st2i.prj.admin.dao.IAdmApplicationDao;
import tn.com.st2i.prj.admin.model.AdmApplication;

import com.easyfaces.dao.tools.ManagerDao;

import org.hibernate.Query;
import org.springframework.stereotype.Repository;

@Repository("admApplicationDao")
public class AdmApplicationDao extends ManagerDao<AdmApplication, Long> implements
		IAdmApplicationDao {

	@Override
	public List<AdmApplication> getListApplications(){
		Query query=null;
		query=createQuery("from AdmApplication order by desApp");
		return findMany(query);
	}
	
}
