package tn.com.st2i.prj.admin.dao.impl;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.Date;
import java.util.List;

import tn.com.st2i.prj.admin.dao.IVAdmUtilisateurDao;
import tn.com.st2i.prj.admin.model.VAdmUtilisateur;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.request.EnumTypOp;
import com.easyfaces.dao.request.Request;
import com.easyfaces.dao.tools.ManagerDao;


import org.hibernate.Query;
import org.springframework.stereotype.Repository;

@Repository("vAdmUtilisateurDao")
public class VAdmUtilisateurDao extends ManagerDao<VAdmUtilisateur, Long> implements
		IVAdmUtilisateurDao {

	@Override
	public List<TableGen> getListVUtilisateurForSearch(String login,
			String name, String cin, Date dateDebutLastCnx,
			Date dateFinLastCnx, Long idProf, Long idEtat) throws Exception {

		Request requete = new Request(VAdmUtilisateur.class, VAdmUtilisateur._idUser);

		requete.addField(VAdmUtilisateur._login);
		requete.addField(VAdmUtilisateur._nomUser);
		requete.addField(VAdmUtilisateur._nomUserAr);
		requete.addField(VAdmUtilisateur._mail);
		requete.addField(VAdmUtilisateur._cin);
		requete.addField(VAdmUtilisateur._desFrUserEtat);
		requete.addField(VAdmUtilisateur._desArUserEtat);

		requete.addClauseString(VAdmUtilisateur._login,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, login);

		requete.addClauseString(VAdmUtilisateur._nomUser,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, name);

		requete.addClauseString(VAdmUtilisateur._cin,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, cin);

		requete.addClauseDate(VAdmUtilisateur._datDerCx,
				EnumTypOp.AllParameter.GREATER_EQUAL, dateDebutLastCnx);
		
								requete.addClauseDate(VAdmUtilisateur._datDerCx,
				EnumTypOp.AllParameter.SMALLER_EQUAL, dateFinLastCnx);
		
		requete.addClauseLong(VAdmUtilisateur._idProfes,
				EnumTypOp.AllParameter.EQUAL, idProf);
		
		requete.addClauseLong(VAdmUtilisateur._idUserEtat,
				EnumTypOp.AllParameter.EQUAL, idEtat);
		
		requete.addOrdre(VAdmUtilisateur._login);

		return getList(requete);
	}

	@Override
	public VAdmUtilisateur findVUserByLoginPwd(String login, String pwd) {
		Query query = null;

		query = createQuery("from VAdmUtilisateur where login=:login and pwd=:pwd");
		query.setString("login", login);
		query.setString("pwd", pwd);

		return findOne(query);
	}

}
