package tn.com.st2i.prj.admin.dao.impl;

/**
 * Generated by easyfaces Hibernate Tools 4.3.1
 */


import java.util.List;

import com.easyfaces.dao.model.TableGen;
import com.easyfaces.dao.request.EnumTypOp;
import com.easyfaces.dao.request.Request;
import com.easyfaces.dao.tools.ManagerDao;

import tn.com.st2i.prj.admin.dao.IVAdmProfilDao;
import tn.com.st2i.prj.admin.model.VAdmProfil;

import org.springframework.stereotype.Repository;

@Repository("vAdmProfilDao")
public class VAdmProfilDao extends ManagerDao<VAdmProfil, Long> implements
		IVAdmProfilDao {

	@Override
	public List<TableGen> getListVProfil(Long idApp, String code, String des,
			Long actif) throws Exception {

		Request requete = new Request(VAdmProfil.class, VAdmProfil._idProfil);

		requete.addField(VAdmProfil._desApp);
		requete.addField(VAdmProfil._desAppAr);
		requete.addField(VAdmProfil._codProfil);
		requete.addField(VAdmProfil._desProfil);
		requete.addField(VAdmProfil._desProfilAr);
		requete.addField(VAdmProfil._desFrActif);
		requete.addField(VAdmProfil._desArActif);

		requete.addClauseString(VAdmProfil._codProfil,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, code);

		requete.addClauseString(VAdmProfil._desProfil,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, des);

		requete.addClauseLong(VAdmProfil._idApp, EnumTypOp.AllParameter.EQUAL,
				idApp);

		requete.addClauseLong(VAdmProfil._FActif, EnumTypOp.AllParameter.EQUAL,
				actif);

		requete.addOrdre(VAdmProfil._desApp);
		requete.addOrdre(VAdmProfil._codProfil);

		return getList(requete);
	}

	@Override
	public List<TableGen> getListVProfilActif(Long idApp, String code,
			String des) throws Exception {

		Request requete = new Request(VAdmProfil.class, VAdmProfil._idProfil);

		requete.addField(VAdmProfil._desApp);
		requete.addField(VAdmProfil._desAppAr);
		requete.addField(VAdmProfil._codProfil);
		requete.addField(VAdmProfil._desProfil);
		requete.addField(VAdmProfil._desProfilAr);

		requete.addClauseString(VAdmProfil._codProfil,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, code);

		requete.addClauseString(VAdmProfil._desProfil,
				EnumTypOp.StringParameter.CENTER_WORD_LIKE, des);

		requete.addClauseLong(VAdmProfil._idApp, EnumTypOp.AllParameter.EQUAL,
				idApp);

		requete.addClauseInteger(VAdmProfil._FActif, EnumTypOp.AllParameter.EQUAL, 1);

		requete.addOrdre(VAdmProfil._desApp);
		requete.addOrdre(VAdmProfil._codProfil);

		return getList(requete);
	}

}
